@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contentType = application/json

POST {{baseUrl}}/books
Content-Type: {{contentType}}

{
    "title": "A busca pela razão",
    "subtitle": "enconte a verdadeira sabedoria",
    "author": "Cavalli",
    "genre": "Terror",
    "cover": "https://m.media-amazon.com/images/I/81SM0D5+DwL._SL1500_.jpg"
}

###
GET {{baseUrl}}/books
Content-Type: {{contentType}}

###
GET {{baseUrl}}/books/6722333a230671699a054041
Content-Type: {{contentType}}

###
PUT {{baseUrl}}/books/6722333a230671699a054041
Content-Type: {{contentType}}

{
  "subtitle": "A honestidade de um GRANDE politico",
  "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113624_84e92bc9-fe5b-4d2c-9c79-5d2153540499.jpg"
}

###
DELETE {{baseUrl}}/books/6722333a230671699a054041
Content-Type: {{contentType}}